### ISSUE TITLE
Error on edit page after authorising GA

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#110]
This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist:  

```
Traceback (most recent call last):
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/francesberriman/Documents/repos/bizarro-cms/venv-bizarro-cms/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/bizarro/view_functions.py", line 116, in decorated_function
    return route_function(*args, **kwargs)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/bizarro/view_functions.py", line 194, in decorated_function
    response = route_function(*args, **kwargs)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/bizarro/views.py", line 278, in branch_edit
    analytics_dict = fetch_google_analytics_for_page(path, f.read())
  File "/Users/francesberriman/Documents/repos/bizarro-cms/bizarro/google_api_functions.py", line 88, in fetch_google_analytics_for_page
    page_path_pattern = get_ga_page_path_pattern(page_path)
  File "/Users/francesberriman/Documents/repos/bizarro-cms/bizarro/google_api_functions.py", line 79, in get_ga_page_path_pattern
    return posixpath.join(ga_domain, page_path_dir, filename_pattern)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by tmaybe** [comment]
@phae can you verify that you're still seeing this bug after c3d2a6787dd592277018507b1f6e5fdf5564a044

**Comment by phae** [comment]
I just pulled latest, and do not seem to be able to trigger this error
anymore! Hooray!
